IF  EXISTS (SELECT *
FROM sys.objects
WHERE object_id = OBJECT_ID(N'[dbo].[PERSONA]') AND type in (N'U'))
DROP TABLE [dbo].[PERSONA]
GO


CREATE TABLE PERSONA
(
    idPersona INT IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    DNI NUMERIC NOT NULL,
    CONSTRAINT PK_PERSONA PRIMARY KEY(idPersona),
    CONSTRAINT UQ_DNI UNIQUE(DNI),
    CONSTRAINT CHK_PERSONA_DNI CHECK(DNI<100000000 AND DNI>9999999),
    CONSTRAINT CHK_PERSONA_NOMBRE CHECK(nombre NOT LIKE '%[^A-Za-z]%')
)
GO

CREATE TABLE Direccion
(
    idDireccion INT IDENTITY,
    asddasd INT NOT NULL,
    direccion VARCHAR(250) NOT NULL,
    CONSTRAINT PK_DIRECCION PRIMARY KEY(idDireccion),
    CONSTRAINT FK_DIRECCION_PERSONA FOREIGN KEY(asddasd) REFERENCES PERSONA(idPersona)
);
GO

/* Insersion de filas a la tabla */
INSERT INTO PERSONA
    (nombre, DNI)
VALUES
    ('A', 10989012)
GO


/* TRY CATCH */
BEGIN TRY
    INSERT INTO PERSONA
        (nombre, DNI)
    VALUES
        ('Juan', 123488),
        ('María', 87621),
        ('Pedro', 98765);
END TRY
BEGIN CATCH
    SELECT GETDATE()
END CATCH
GO

/* TABLA VER */
SELECT *
FROM PERSONA
GO

/* TRANSACTION */

BEGIN TRANSACTION

ROLLBACK
COMMIT

SELECT p.nombre, d.direccion
FROM Persona p
INNER JOIN Direccion d ON p.idPersona = d.idPersona;

SELECT p.nombre, d.direccion
FROM Persona p
LEFT JOIN Direccion d ON p.idPersona = d.idPersona;



BEGIN TRANSACTION

INSERT INTO PERSONA
    (nombre, DNI)
VALUES
    ('C', 13345612)
        SELECT * FROM PERSONA

ROLLBACK

 SELECT * FROM PERSONA

BEGIN TRANSACTION 

ROLLBACK

COMMIT

BEGIN TRANSACTION
BEGIN TRY
        INSERT INTO PERSONA(nombre, DNI)VALUES('Juan', 123488),('María', 87621),('Pedro', 98765)
END TRY
BEGIN CATCH
    PRINT('NO GUARDO POR ERRORES')
    ROLLBACK
END CATCH
GO
COMMIT







ALTER PROCEDURE USP_PROCESS
	@PARAMETRO1 INT, @PARAMETRO2 INT
AS
BEGIN
    DECLARE @SUMA INT = @PARAMETRO1 + @PARAMETRO2;
    
    SELECT @SUMA,* FROM PERSONA WHERE PERSONA.idPersona = @PARAMETRO1
END
GO

EXEC USP_PROCESS 5,10
GO




















