-- RESTRICCION CHECK --
USE BDJURIDICO;
GO
-- CLIENTE CHK
ALTER TABLE CLIENTE
ADD CONSTRAINT CHK_CLIENTE_CORREO CHECK (CORREO LIKE '%@%._%' AND CORREO NOT LIKE '%@%@%'),
CONSTRAINT CHK_CLIENTE_DNI CHECK (DNI<100000000 AND DNI>9999999);
GO

-- EXPEDIENTE --
ALTER TABLE EXPEDIENTE
    ADD CONSTRAINT CHCK_EXPEDIENTE_FECHA CHECK
    (
        FECHAFINALIZACION IS NULL OR FECHAFINALIZACION >= FECHAINICIO
    );
GO










-------------------meo 

