-- RESTRICCION FOREING KEY --
USE BDJURIDICO;
GO
-- EXPEDIENTE -- 
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT FK_EXPEDIENTE_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO),
CONSTRAINT FK_EXPEDIENTE_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

-- ACTIVIDAD --
ALTER TABLE ACTIVIDAD
ADD CONSTRAINT FK_ACTIVIDAD_EXPEDIENTE FOREIGN KEY (IDEXPEDIENTE) REFERENCES EXPEDIENTE(IDEXPEDIENTE)
GO