-- RESTRICCION UNIQUE --
USE BDJURIDICO;
GO

-- CLIENTE  -- 
ALTER TABLE CLIENTE
ADD CONSTRAINT UQ_CLIENTE_DNI UNIQUE (DNI),
CONSTRAINT UQ_CLIENTE_CORREO UNIQUE (CORREO),
CONSTRAINT UQ_CLIENTE_NOMBRE UNIQUE (NOMBRE);
GO
-- nada que ver
-- ESTADO -- 
ALTER TABLE ESTADO
ADD CONSTRAINT UQ_ESTADO_NOMBRE UNIQUE (NOMBRE);
GO

-- CLIENTE  -- 
ALTER TABLE CLIENTE
ADD CONSTRAINT UQ_CLIENTE_DNI UNIQUE (DNI),
CONSTRAINT UQ_CLIENTE_CORREO UNIQUE (CORREO);
GO
