USE BDJURIDICO;
GO
-- CREACION DE TABLAS
-- EXPEDIENTE --
CREATE TABLE EXPEDIENTE
(
    IDEXPEDIENTE INTEGER IDENTITY,
    IDCLIENTE INTEGER NOT NULL,
    FECHAINICIO DATETIME NOT NULL,
    FECHAFINALIZACION DATETIME NULL,
    IDESTADO INTEGER NOT NULL
);
GO

-- CLIENTE --
CREATE TABLE CLIENTE
(
    IDCLIENTE INTEGER IDENTITY,
    DNI NUMERIC(8) NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL,
    CORREO VARCHAR(250) NOT NULL
);
GO

-- ESTADO --
CREATE TABLE ESTADO
(
    IDESTADO INTEGER IDENTITY,
    NOMBRE VARCHAR(15) NOT NULL
);
GO

-- ACTIVIDAD --
CREATE TABLE ACTIVIDAD
(
    IDACTIVIDAD INTEGER IDENTITY,
    IDEXPEDIENTE INTEGER NOT NULL,
    NOMBREACTIVIDAD VARCHAR(50),
    FECHA DATETIME NOT NULL
);
GO

