CREATE DATABASE BDJURIDICO;
GO

USE BDJURIDICO;
GO
-- DESAFIO 1
-- CREACION DE TABLAS
-- EXPEDIENTE --
CREATE TABLE EXPEDIENTE
(
    IDEXPEDIENTE INTEGER IDENTITY,
    IDCLIENTE INTEGER NOT NULL,
    FECHAINICIO DATETIME NOT NULL,
    FECHAFINALIZACION DATETIME NULL,
    IDESTADO INTEGER NOT NULL
);
GO

-- CLIENTE --
CREATE TABLE CLIENTE
(
    IDCLIENTE INTEGER IDENTITY,
    DNI NUMERIC(8) NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL,
    CORREO VARCHAR(250) NOT NULL
);
GO

-- ESTADO --
CREATE TABLE ESTADO
(
    IDESTADO INTEGER IDENTITY,
    NOMBRE VARCHAR(15) NOT NULL
);
GO

-- ACTIVIDAD --
CREATE TABLE ACTIVIDAD
(
    IDACTIVIDAD INTEGER IDENTITY,
    IDEXPEDIENTE INTEGER NOT NULL,
    NOMBREACTIVIDAD VARCHAR(50),
    FECHA DATETIME NOT NULL
);
GO
-- DESAFIO 2
-- RESTRICCION PRIMARY KEY --

-- EXPEDIENTE --
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT PK_EXPEDIENTE PRIMARY KEY (IDEXPEDIENTE);
GO


-- CLIENTE --
ALTER TABLE CLIENTE
    ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE);
GO


-- ESTADO --
ALTER TABLE ESTADO
    ADD CONSTRAINT PK_ESTADO PRIMARY KEY(IDESTADO);
GO


-- ACTIVIDAD --
ALTER TABLE ACTIVIDAD
    ADD CONSTRAINT PK_ACTIVIDAD PRIMARY KEY(IDACTIVIDAD);
GO
-- DESAFIO 3
-- RESTRICCION FOREING KEY --
-- EXPEDIENTE -- 
ALTER TABLE EXPEDIENTE
ADD CONSTRAINT FK_EXPEDIENTE_ESTADO FOREIGN KEY (IDESTADO) REFERENCES ESTADO(IDESTADO),
CONSTRAINT FK_EXPEDIENTE_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
GO

-- ACTIVIDAD --
ALTER TABLE ACTIVIDAD
ADD CONSTRAINT FK_ACTIVIDAD_EXPEDIENTE FOREIGN KEY (IDEXPEDIENTE) REFERENCES EXPEDIENTE(IDEXPEDIENTE)
GO
-- DESAFIO 4
-- RESTRICCION UNIQUE --

-- CLIENTE -- 
ALTER TABLE CLIENTE
ADD CONSTRAINT UQ_CLIENTE_DNI UNIQUE (DNI),
CONSTRAINT UQ_CLIENTE_CORREO UNIQUE (CORREO),
CONSTRAINT UQ_CLIENTE_NOMBRE UNIQUE (NOMBRE);
GO
-- DESAFIO 5
-- RESTRICCION CHECK --

-- CLIENTE CHK
ALTER TABLE CLIENTE
ADD CONSTRAINT CHK_CLIENTE_CORREO CHECK (CORREO LIKE '%@%._%' AND CORREO NOT LIKE '%@%@%'),
CONSTRAINT CHK_CLIENTE_DNI CHECK (DNI<100000000 AND DNI>9999999);
GO

-- EXPEDIENTE --
ALTER TABLE EXPEDIENTE
    ADD CONSTRAINT CHCK_EXPEDIENTE_FECHA CHECK
    (
        FECHAFINALIZACION IS NULL OR FECHAFINALIZACION >= FECHAINICIO
    );
GO