-- EXERCISE 6
SELECT
    *
FROM BDJURIDICO..CLIENTE
WHERE CORREO IS NULL;
GO
-- EXERCISE 7
SELECT
    EXPEDIENTE.IDEXPEDIENTE
      , EXPEDIENTE.IDCLIENTE
      , EXPEDIENTE.FECHAINICIO
      , EXPEDIENTE.FECHAFINALIZACION
      , EXPEDIENTE.IDESTADO,
    ESTADO.NOMBRE
FROM BDJURIDICO..EXPEDIENTE
    JOIN BDJURIDICO..ESTADO ON EXPEDIENTE.IDESTADO = ESTADO.IDESTADO
WHERE ESTADO.NOMBRE = 'archivado';
GO
-- EXERCISE 8
SELECT
    *
FROM BDJURIDICO..ACTIVIDAD
WHERE IDEXPEDIENTE = 3 AND FECHA BETWEEN '2023-10-05' AND '2023-10-20';
GO
-- EXERCISE 9
SELECT
    *
FROM BDJURIDICO..EXPEDIENTE
WHERE DATEDIFF(MONTH, FECHAINICIO, FECHAFINALIZACION)>=18
GO
-- EXERCISE 10
SELECT
    *
FROM BDJURIDICO..EXPEDIENTE
WHERE IDCLIENTE = 4 AND IDESTADO = 3 AND DATEDIFF(MONTH, FECHAINICIO, FECHAFINALIZACION)<18
GO
